export interface BeneficiarioAfiliacion{
            FechaConsulta:string,
            Id:number,
            BocaDeExpendio,
            UsuarioApodovallejosl,
            CUITTitular,
            NOMBRETitular,
            Documento,
            TipoDocumento,
            TipoDocumentoDescripcion,
            PlanBeneficiario,
            NroPlan,
            Secuencia,
            Sexo,
            Uatre,
            EsVirtual,
            Nombre,
            EstadoCobertura,
            EnCondiciones,
            OrigenBeneficiario,
            Localidad,
            Provincia,
            FechaDeAlta,
            FechaNacimiento,
            Edad,
            FechaCarencia1,
            FechaCarencia2,
            AplicaCoseguro,
            CoberturaToString,
            CarenciaToString,
            TipoConsulta,
            MesConsulta,
            Correlativo,
            Haydatos,
            Parentesco,
            Discapacidad,
            id_beneficiario,
            TipoAfiliado,
            Rural,
            EsASIMM,
            EsNoRural,
            TraspasoVigente,
            ConsultaExcepcional,
            RangoTraspaso,
            FechaVencimientoPMI,
            BocaExpendioDescripcion,
            FechaNacimientoToString,
            EdadToString,
            UatreToString
}

/*
[
    {
        "FechaConsulta": "2020-09-17T08:27:13.9405152-03:00",
        "Id": "0",
        "BocaDeExpendio": "6770000546",
        "UsuarioApodo": "OSPRERA\\vallejosl",
        "CUITTitular": "23354964309",
        "NOMBRETitular": "VALLEJOS LUCAS MATIAS         ",
        "Documento": "35496430",
        "TipoDocumento": "5",
        "TipoDocumentoDescripcion": "DNI",
        "PlanBeneficiario": "10-Ctante c/·ltimo mes en condici",
        "NroPlan": 10,
        "Secuencia": "0",
        "Sexo": "M",
        "Uatre": "True",
        "EsVirtual": " ",
        "Nombre": "VALLEJOS LUCAS MATIAS         ",
        "EstadoCobertura": "Si",
        "EnCondiciones": "True",
        "OrigenBeneficiario": "RURAL",
        "Localidad": "Resistencia                   ",
        "Provincia": "CHACO",
        "FechaDeAlta": "10/06/2013",
        "FechaNacimiento": "1991-04-29T00:00:00",
        "Edad": "29",
        "FechaCarencia1": null,
        "FechaCarencia2": null,
        "AplicaCoseguro": "SI",
        "CoberturaToString": "BASICA",
        "CarenciaToString": "",
        "GetEstado": "En Condiciones",
        "TipoConsulta": "Padron Vigente",
        "MesConsulta": null,
        "Correlativo": "2484227",
        "Haydatos": true,
        "Parentesco": "TITULAR",
        "Discapacidad": null,
        "id_beneficiario": "2335496430953549643000R",
        "TipoAfiliado": "O",
        "Rural": "RU",
        "EsASIMM": false,
        "EsNoRural": false,
        "TraspasoVigente": false,
        "ConsultaExcepcional": false,
        "RangoTraspaso": "",
        "TipoBeneficiarioDetalle": "",
        "FechaVencimientoDiscapacidad": null,
        "FechaVencimientoPMI": null,
        "BocaExpendioDescripcion": "RESISTENCIA",
        "FechaNacimientoToString": "29/04/1991",
        "EdadToString": "(29 Años)",
        "UatreToString": "Si"
    }
]
*/

export interface BeneficiarioComun{
            Id,
            PersonaId,
            Nombre,
            NumeroDocumento,
            Sexo,
            FechaNacimiento,
            Edad,
            getEstado,
            TipoDeDocumentoId,
            TipoDeDocumentoResumen,
            TipoDeBeneficiarioDescripcion,
            Titular,
            ParentescoDescripcion,
            GrupoFamiliarTitularNombre,
            GrupoFamiliarTitularCuil,
            BocaDeExpendioId,
            BocaDeExpendioDescripcion,
            BocaDeExpendioDescripcionCompleta,
            BocaDeExpendioProvinciaId,
            Localidad,
            BocaDeExpendioProvinciaDescripcion,
            Cuil,
            Origen,
            EnCondicion,
            AltaProvisoria,
            FechaAlta,
            FechaAltaToString,
            FechaNacimientoToString,
            Uatre,
            Estado,
            UatreToString,
            TraspasoVigente,
            RangoTraspaso,
            Carencias,
            AccidenteVigente,
            AccidenteEstado,
            AccidenteDescripcion,
            AccidenteFechaDesdeToShortDateString,
            AccidenteFechaHastaToShortDateString,
            CoberturaToString,
            SexoToString,
            pagina,
            total,
            rpp,
            CarenciaToString,
            Coseguro,
            PlanBeneficiario,
            NoRural,
            NoRuralDescripcion,
            MotivoBajaRural,
            MotivoBajaMonotributista,
            FechaCarencia1,
            FechaCarencia2,
            FechaCarencia1ToString,
            FechaCarencia2ToString,
}